export const metadata = {
  title: "Minami Haruto",
  description:
    "Hello! I'm Minami Haruto, a Senior Web Developer based in Osaka, Japan. I love to create beautiful and functional websites and apps.",
  name: "Haruto",
  fullName: "Minami Haruto",
  slogan: "Full-stack Developer",
  picture: "/assets/blog/authors/angryred027.jpg",
  tags: [
    "Minami Haruto",
    "Minami",
    "Haruto",
    "Angry Red",
    "angryred027",
    "angry",
    "red",
    "angryred",
    "full-stack developer",
    "Frontend Developer",
    "Frontend",
    "Developer",
    "UX Designer",
    "Osaka",
    "Japan",
    "Sakai",
    "Web Developer",
    "Next.js",
    "Best React Developer",
    "React",
    "React Developer",
    "UX Designer",
    "full-stack",
    "portfolio",
    "Next.js developer",
    "TailwindCSS",
  ],

  links: {
    website: "https://minamiharuto.vercel.app/",
    github: "https://gitlab.com/angryred027",
    email: "mailto:minamiharuto727@gmail.com",
    cv: "/files/MinamiHaruto.pdf"
  },

  homeOgImage: "/assets/thumbnail.png",
};
